[package]
name = "sqlparser_parse"
version = "0.1.0"
authors = []
edition = "2018"

[lib]
name = "sqlparser_parse"
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
rustler = "0.26.0"
sqlparser = "0.30.0"